version: "3.9"
services:
  api:
    build: .
    env_file: .env
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  front:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./front:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
