[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B"]
ignore = []
target-version = "py312"

[tool.black]
line-length = 100

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
ignore_missing_imports = true
check_untyped_defs = true
