# pyproject.toml
[tool.ruff]
line-length = 100
target-version = "py312"  # <— important : autorise `X | None`

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = []

[tool.ruff.format]
quote-style = "double"
