[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
# On NE sélectionne PAS "I" -> plus d'erreurs d'import non trié
select = ["E", "F", "UP", "B"]
ignore = []
per-file-ignores = { "app/schemas.py" = ["UP045"] }

[tool.ruff.format]
quote-style = "double"
