name: Epic
description: Grand objectif découpé en user stories
labels: ["type: epic"]
body:
  - type: input
    id: goal
    attributes:
      label: Objectif
      description: Résume l'impact utilisateur et business
      placeholder: Ex. "Permettre une recherche 'langage naturel'"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Périmètre / Non-Objectifs
      description: Ce qui est inclus et exclu
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d'acceptation
      description: Liste de "Given/When/Then" ou checklist de done
  - type: textarea
    id: notes
    attributes:
      label: Notes / Liens
      description: Liens docs, maquettes, tech notes
