name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          src: "./"
          # On évite la règle I001 (imports triés) en sélectionnant seulement E,F,UP,B
          args: "check . --select E,F,UP,B"

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      # Pour que `from app...` fonctionne en CI
      PYTHONPATH: ${{ github.workspace }}
      # Dummies pour les tests (pas d'appel réseau)
      AMADEUS_CLIENT_ID: "dummy"
      AMADEUS_CLIENT_SECRET: "dummy"
      AMADEUS_HOST: "https://example.invalid"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: python -m pytest -q
